/**
 * MARD 拼豆色卡数据模块
 * 提供标准色号、HEX 参考值与系列分组，供颜色选择器使用
 */

/** 单个 MARD 色号 */
export type MardColor = {
  code: string
  hex: string
  series: string
}

/** MARD 完整色卡（291 色，HEX 为屏幕预览参考值） */
export const MARDCOLORS: MardColor[] = [
  { code: 'A1', hex: '#FAF4C8', series: 'A' },
  { code: 'A2', hex: '#FFFFD5', series: 'A' },
  { code: 'A3', hex: '#FEFF8B', series: 'A' },
  { code: 'A4', hex: '#FBED56', series: 'A' },
  { code: 'A5', hex: '#F4D738', series: 'A' },
  { code: 'A6', hex: '#FEAC4C', series: 'A' },
  { code: 'A7', hex: '#FE8B4C', series: 'A' },
  { code: 'A8', hex: '#FFDA45', series: 'A' },
  { code: 'A9', hex: '#FF995B', series: 'A' },
  { code: 'A10', hex: '#F77C31', series: 'A' },
  { code: 'A11', hex: '#FFDD99', series: 'A' },
  { code: 'A12', hex: '#FE9F72', series: 'A' },
  { code: 'A13', hex: '#FFC365', series: 'A' },
  { code: 'A14', hex: '#FD543D', series: 'A' },
  { code: 'A15', hex: '#FFF365', series: 'A' },
  { code: 'A16', hex: '#FFFF9F', series: 'A' },
  { code: 'A17', hex: '#FFE36E', series: 'A' },
  { code: 'A18', hex: '#FEBE7D', series: 'A' },
  { code: 'A19', hex: '#FD7C72', series: 'A' },
  { code: 'A20', hex: '#FFD568', series: 'A' },
  { code: 'A21', hex: '#FFE395', series: 'A' },
  { code: 'A22', hex: '#F4F57D', series: 'A' },
  { code: 'A23', hex: '#E6C9B7', series: 'A' },
  { code: 'A24', hex: '#F7F8A2', series: 'A' },
  { code: 'A25', hex: '#FFD67D', series: 'A' },
  { code: 'A26', hex: '#FFC830', series: 'A' },
  { code: 'B1', hex: '#E6EE31', series: 'B' },
  { code: 'B2', hex: '#63F347', series: 'B' },
  { code: 'B3', hex: '#9EF780', series: 'B' },
  { code: 'B4', hex: '#5DE035', series: 'B' },
  { code: 'B5', hex: '#35E352', series: 'B' },
  { code: 'B6', hex: '#65E2A6', series: 'B' },
  { code: 'B7', hex: '#3DAF80', series: 'B' },
  { code: 'B8', hex: '#1C9C4F', series: 'B' },
  { code: 'B9', hex: '#27523A', series: 'B' },
  { code: 'B10', hex: '#95D3C2', series: 'B' },
  { code: 'B11', hex: '#5D722A', series: 'B' },
  { code: 'B12', hex: '#166F41', series: 'B' },
  { code: 'B13', hex: '#CAEB7B', series: 'B' },
  { code: 'B14', hex: '#ADE946', series: 'B' },
  { code: 'B15', hex: '#2E5132', series: 'B' },
  { code: 'B16', hex: '#C5ED9C', series: 'B' },
  { code: 'B17', hex: '#9BB13A', series: 'B' },
  { code: 'B18', hex: '#E6EE49', series: 'B' },
  { code: 'B19', hex: '#24B88C', series: 'B' },
  { code: 'B20', hex: '#C2F0CC', series: 'B' },
  { code: 'B21', hex: '#156A6B', series: 'B' },
  { code: 'B22', hex: '#0B3C43', series: 'B' },
  { code: 'B23', hex: '#303A21', series: 'B' },
  { code: 'B24', hex: '#EEFCA5', series: 'B' },
  { code: 'B25', hex: '#4E846D', series: 'B' },
  { code: 'B26', hex: '#8D7A35', series: 'B' },
  { code: 'B27', hex: '#CCE1AF', series: 'B' },
  { code: 'B28', hex: '#9EE5B9', series: 'B' },
  { code: 'B29', hex: '#C5E254', series: 'B' },
  { code: 'B30', hex: '#E2FCB1', series: 'B' },
  { code: 'B31', hex: '#B0E792', series: 'B' },
  { code: 'B32', hex: '#9CAB5A', series: 'B' },
  { code: 'C1', hex: '#E8FFE7', series: 'C' },
  { code: 'C2', hex: '#A9F9FC', series: 'C' },
  { code: 'C3', hex: '#A0E2FB', series: 'C' },
  { code: 'C4', hex: '#41CCFF', series: 'C' },
  { code: 'C5', hex: '#01ACEB', series: 'C' },
  { code: 'C6', hex: '#50AAF0', series: 'C' },
  { code: 'C7', hex: '#3677D2', series: 'C' },
  { code: 'C8', hex: '#0F54C0', series: 'C' },
  { code: 'C9', hex: '#324BCA', series: 'C' },
  { code: 'C10', hex: '#3EBCE2', series: 'C' },
  { code: 'C11', hex: '#28DDDE', series: 'C' },
  { code: 'C12', hex: '#1C334D', series: 'C' },
  { code: 'C13', hex: '#CDE8FF', series: 'C' },
  { code: 'C14', hex: '#D5FDFF', series: 'C' },
  { code: 'C15', hex: '#22C4C6', series: 'C' },
  { code: 'C16', hex: '#1557A8', series: 'C' },
  { code: 'C17', hex: '#04D1F6', series: 'C' },
  { code: 'C18', hex: '#1D3344', series: 'C' },
  { code: 'C19', hex: '#1887A2', series: 'C' },
  { code: 'C20', hex: '#176DAF', series: 'C' },
  { code: 'C21', hex: '#BEDDFF', series: 'C' },
  { code: 'C22', hex: '#67B4BE', series: 'C' },
  { code: 'C23', hex: '#C8E2FF', series: 'C' },
  { code: 'C24', hex: '#7CC4FF', series: 'C' },
  { code: 'C25', hex: '#A9E5E5', series: 'C' },
  { code: 'C26', hex: '#3CAED8', series: 'C' },
  { code: 'C27', hex: '#D3DFFA', series: 'C' },
  { code: 'C28', hex: '#BBCFED', series: 'C' },
  { code: 'C29', hex: '#34488E', series: 'C' },
  { code: 'D1', hex: '#AEB4F2', series: 'D' },
  { code: 'D2', hex: '#858EDD', series: 'D' },
  { code: 'D3', hex: '#2F54AF', series: 'D' },
  { code: 'D4', hex: '#182A84', series: 'D' },
  { code: 'D5', hex: '#B843C5', series: 'D' },
  { code: 'D6', hex: '#AC7BDE', series: 'D' },
  { code: 'D7', hex: '#8854B3', series: 'D' },
  { code: 'D8', hex: '#E2D3FF', series: 'D' },
  { code: 'D9', hex: '#D5B9F8', series: 'D' },
  { code: 'D10', hex: '#361851', series: 'D' },
  { code: 'D11', hex: '#B9BAE1', series: 'D' },
  { code: 'D12', hex: '#DE9AD4', series: 'D' },
  { code: 'D13', hex: '#B90095', series: 'D' },
  { code: 'D14', hex: '#8B279B', series: 'D' },
  { code: 'D15', hex: '#2F1F90', series: 'D' },
  { code: 'D16', hex: '#E3E1EE', series: 'D' },
  { code: 'D17', hex: '#C4D4F6', series: 'D' },
  { code: 'D18', hex: '#A45EC7', series: 'D' },
  { code: 'D19', hex: '#D8C3D7', series: 'D' },
  { code: 'D20', hex: '#9C32B2', series: 'D' },
  { code: 'D21', hex: '#9A009B', series: 'D' },
  { code: 'D22', hex: '#333A95', series: 'D' },
  { code: 'D23', hex: '#EBDAFC', series: 'D' },
  { code: 'D24', hex: '#7786E5', series: 'D' },
  { code: 'D25', hex: '#494FC7', series: 'D' },
  { code: 'D26', hex: '#DFC2F8', series: 'D' },
  { code: 'E1', hex: '#FDD3CC', series: 'E' },
  { code: 'E2', hex: '#FEC0DF', series: 'E' },
  { code: 'E3', hex: '#FFB7E7', series: 'E' },
  { code: 'E4', hex: '#E8649E', series: 'E' },
  { code: 'E5', hex: '#F551A2', series: 'E' },
  { code: 'E6', hex: '#F13D74', series: 'E' },
  { code: 'E7', hex: '#C63478', series: 'E' },
  { code: 'E8', hex: '#FFDBE9', series: 'E' },
  { code: 'E9', hex: '#E970CC', series: 'E' },
  { code: 'E10', hex: '#D33793', series: 'E' },
  { code: 'E11', hex: '#FCDDD2', series: 'E' },
  { code: 'E12', hex: '#F78FC3', series: 'E' },
  { code: 'E13', hex: '#B5006D', series: 'E' },
  { code: 'E14', hex: '#FFD1BA', series: 'E' },
  { code: 'E15', hex: '#F8C7C9', series: 'E' },
  { code: 'E16', hex: '#FFF3EB', series: 'E' },
  { code: 'E17', hex: '#FFE2EA', series: 'E' },
  { code: 'E18', hex: '#FFC7DB', series: 'E' },
  { code: 'E19', hex: '#FEBAD5', series: 'E' },
  { code: 'E20', hex: '#D8C7D1', series: 'E' },
  { code: 'E21', hex: '#BD9DA1', series: 'E' },
  { code: 'E22', hex: '#B785A1', series: 'E' },
  { code: 'E23', hex: '#937A8D', series: 'E' },
  { code: 'E24', hex: '#E1BCE8', series: 'E' },
  { code: 'F1', hex: '#FD957B', series: 'F' },
  { code: 'F2', hex: '#FC3D46', series: 'F' },
  { code: 'F3', hex: '#F74941', series: 'F' },
  { code: 'F4', hex: '#FC283C', series: 'F' },
  { code: 'F5', hex: '#E7002F', series: 'F' },
  { code: 'F6', hex: '#943630', series: 'F' },
  { code: 'F7', hex: '#971937', series: 'F' },
  { code: 'F8', hex: '#BC0028', series: 'F' },
  { code: 'F9', hex: '#E2677A', series: 'F' },
  { code: 'F10', hex: '#8A4526', series: 'F' },
  { code: 'F11', hex: '#5A2121', series: 'F' },
  { code: 'F12', hex: '#FD4E6A', series: 'F' },
  { code: 'F13', hex: '#F35744', series: 'F' },
  { code: 'F14', hex: '#FFA9AD', series: 'F' },
  { code: 'F15', hex: '#D30022', series: 'F' },
  { code: 'F16', hex: '#FEC2A6', series: 'F' },
  { code: 'F17', hex: '#E69C79', series: 'F' },
  { code: 'F18', hex: '#D37C46', series: 'F' },
  { code: 'F19', hex: '#C1444A', series: 'F' },
  { code: 'F20', hex: '#CD9391', series: 'F' },
  { code: 'F21', hex: '#F7B4C6', series: 'F' },
  { code: 'F22', hex: '#FDC0D0', series: 'F' },
  { code: 'F23', hex: '#F67E66', series: 'F' },
  { code: 'F24', hex: '#E698AA', series: 'F' },
  { code: 'F25', hex: '#E54B4F', series: 'F' },
  { code: 'G1', hex: '#FFE2CE', series: 'G' },
  { code: 'G2', hex: '#FFC4AA', series: 'G' },
  { code: 'G3', hex: '#F4C3A5', series: 'G' },
  { code: 'G4', hex: '#E1B383', series: 'G' },
  { code: 'G5', hex: '#EDB045', series: 'G' },
  { code: 'G6', hex: '#E99C17', series: 'G' },
  { code: 'G7', hex: '#9D5B3E', series: 'G' },
  { code: 'G8', hex: '#753832', series: 'G' },
  { code: 'G9', hex: '#E6B483', series: 'G' },
  { code: 'G10', hex: '#D98C39', series: 'G' },
  { code: 'G11', hex: '#E0C593', series: 'G' },
  { code: 'G12', hex: '#FFC890', series: 'G' },
  { code: 'G13', hex: '#B7714A', series: 'G' },
  { code: 'G14', hex: '#8D614C', series: 'G' },
  { code: 'G15', hex: '#FCF9E0', series: 'G' },
  { code: 'G16', hex: '#F2D9BA', series: 'G' },
  { code: 'G17', hex: '#78524B', series: 'G' },
  { code: 'G18', hex: '#FFE4CC', series: 'G' },
  { code: 'G19', hex: '#E07935', series: 'G' },
  { code: 'G20', hex: '#A94023', series: 'G' },
  { code: 'G21', hex: '#B88558', series: 'G' },
  { code: 'H1', hex: '#FDFBFF', series: 'H' },
  { code: 'H2', hex: '#FEFFFF', series: 'H' },
  { code: 'H3', hex: '#B6B1BA', series: 'H' },
  { code: 'H4', hex: '#89858C', series: 'H' },
  { code: 'H5', hex: '#48464E', series: 'H' },
  { code: 'H6', hex: '#2F2B2F', series: 'H' },
  { code: 'H7', hex: '#000000', series: 'H' },
  { code: 'H8', hex: '#E7D6DB', series: 'H' },
  { code: 'H9', hex: '#EDEDED', series: 'H' },
  { code: 'H10', hex: '#EEE9EA', series: 'H' },
  { code: 'H11', hex: '#CECDD5', series: 'H' },
  { code: 'H12', hex: '#FFF5ED', series: 'H' },
  { code: 'H13', hex: '#F5ECD2', series: 'H' },
  { code: 'H14', hex: '#CFD7D3', series: 'H' },
  { code: 'H15', hex: '#98A6A8', series: 'H' },
  { code: 'H16', hex: '#1D1414', series: 'H' },
  { code: 'H17', hex: '#F1EDED', series: 'H' },
  { code: 'H18', hex: '#FFFDF0', series: 'H' },
  { code: 'H19', hex: '#F6EFE2', series: 'H' },
  { code: 'H20', hex: '#949FA3', series: 'H' },
  { code: 'H21', hex: '#FFFBE1', series: 'H' },
  { code: 'H22', hex: '#CACAD4', series: 'H' },
  { code: 'H23', hex: '#9A9D94', series: 'H' },
  { code: 'M1', hex: '#BCC6B8', series: 'M' },
  { code: 'M2', hex: '#8AA386', series: 'M' },
  { code: 'M3', hex: '#697D80', series: 'M' },
  { code: 'M4', hex: '#E3D2BC', series: 'M' },
  { code: 'M5', hex: '#D0CCAA', series: 'M' },
  { code: 'M6', hex: '#B0A782', series: 'M' },
  { code: 'M7', hex: '#B4A497', series: 'M' },
  { code: 'M8', hex: '#B38281', series: 'M' },
  { code: 'M9', hex: '#A58767', series: 'M' },
  { code: 'M10', hex: '#C5B2BC', series: 'M' },
  { code: 'M11', hex: '#9F7594', series: 'M' },
  { code: 'M12', hex: '#644749', series: 'M' },
  { code: 'M13', hex: '#D19066', series: 'M' },
  { code: 'M14', hex: '#C77362', series: 'M' },
  { code: 'M15', hex: '#757D78', series: 'M' },
  { code: 'P1', hex: '#FCF7F8', series: 'P' },
  { code: 'P2', hex: '#B0A9AC', series: 'P' },
  { code: 'P3', hex: '#AFDCAB', series: 'P' },
  { code: 'P4', hex: '#FEA49F', series: 'P' },
  { code: 'P5', hex: '#EE8C3E', series: 'P' },
  { code: 'P6', hex: '#5FD0A7', series: 'P' },
  { code: 'P7', hex: '#EB9270', series: 'P' },
  { code: 'P8', hex: '#F0D958', series: 'P' },
  { code: 'P9', hex: '#D9D9D9', series: 'P' },
  { code: 'P10', hex: '#D9C7EA', series: 'P' },
  { code: 'P11', hex: '#F3ECC9', series: 'P' },
  { code: 'P12', hex: '#E6EEF2', series: 'P' },
  { code: 'P13', hex: '#AACBEF', series: 'P' },
  { code: 'P14', hex: '#337680', series: 'P' },
  { code: 'P15', hex: '#668575', series: 'P' },
  { code: 'P16', hex: '#FEBF45', series: 'P' },
  { code: 'P17', hex: '#FEA324', series: 'P' },
  { code: 'P18', hex: '#FEB89F', series: 'P' },
  { code: 'P19', hex: '#FFFEEC', series: 'P' },
  { code: 'P20', hex: '#FEBECF', series: 'P' },
  { code: 'P21', hex: '#ECBEBF', series: 'P' },
  { code: 'P22', hex: '#E4A89F', series: 'P' },
  { code: 'P23', hex: '#A56268', series: 'P' },
  { code: 'Q1', hex: '#F2A5E8', series: 'Q' },
  { code: 'Q2', hex: '#E9EC91', series: 'Q' },
  { code: 'Q3', hex: '#FFFF00', series: 'Q' },
  { code: 'Q4', hex: '#FFEBFA', series: 'Q' },
  { code: 'Q5', hex: '#76CEDE', series: 'Q' },
  { code: 'R1', hex: '#D50D21', series: 'R' },
  { code: 'R2', hex: '#F92F83', series: 'R' },
  { code: 'R3', hex: '#FD8324', series: 'R' },
  { code: 'R4', hex: '#F8EC31', series: 'R' },
  { code: 'R5', hex: '#35C75B', series: 'R' },
  { code: 'R6', hex: '#238891', series: 'R' },
  { code: 'R7', hex: '#19779D', series: 'R' },
  { code: 'R8', hex: '#1A60C3', series: 'R' },
  { code: 'R9', hex: '#9A56B4', series: 'R' },
  { code: 'R10', hex: '#FFDB4C', series: 'R' },
  { code: 'R11', hex: '#FFEBFA', series: 'R' },
  { code: 'R12', hex: '#D8D5CE', series: 'R' },
  { code: 'R13', hex: '#55514C', series: 'R' },
  { code: 'R14', hex: '#9FE4DF', series: 'R' },
  { code: 'R15', hex: '#77CEE9', series: 'R' },
  { code: 'R16', hex: '#3ECFCA', series: 'R' },
  { code: 'R17', hex: '#4A867A', series: 'R' },
  { code: 'R18', hex: '#7FCD9D', series: 'R' },
  { code: 'R19', hex: '#CDE55D', series: 'R' },
  { code: 'R20', hex: '#E8C7B4', series: 'R' },
  { code: 'R21', hex: '#AD6F3C', series: 'R' },
  { code: 'R22', hex: '#6C372F', series: 'R' },
  { code: 'R23', hex: '#FEB872', series: 'R' },
  { code: 'R24', hex: '#F3C1C0', series: 'R' },
  { code: 'R25', hex: '#C9675E', series: 'R' },
  { code: 'R26', hex: '#D293BE', series: 'R' },
  { code: 'R27', hex: '#EA8CB1', series: 'R' },
  { code: 'R28', hex: '#9C87D6', series: 'R' },
  { code: 'T1', hex: '#FFFFFF', series: 'T' },
  { code: 'Y1', hex: '#FD6FB4', series: 'Y' },
  { code: 'Y2', hex: '#FEB481', series: 'Y' },
  { code: 'Y3', hex: '#D7FAA0', series: 'Y' },
  { code: 'Y4', hex: '#8BDBFA', series: 'Y' },
  { code: 'Y5', hex: '#E987EA', series: 'Y' },
  { code: 'ZG1', hex: '#DAABB3', series: 'ZG' },
  { code: 'ZG2', hex: '#D6AA87', series: 'ZG' },
  { code: 'ZG3', hex: '#C1BD8D', series: 'ZG' },
  { code: 'ZG4', hex: '#96869F', series: 'ZG' },
  { code: 'ZG5', hex: '#8490A6', series: 'ZG' },
  { code: 'ZG6', hex: '#94BFE2', series: 'ZG' },
  { code: 'ZG7', hex: '#E2A9D2', series: 'ZG' },
  { code: 'ZG8', hex: '#AB91C0', series: 'ZG' },
]

/** 色卡系列列表 */
export const MARDSERIES = [
  '全部',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'M',
  'P',
  'Q',
  'R',
  'T',
  'Y',
  'ZG',
] as const

/**
 * 按系列筛选 MARD 色卡
 * @param series 系列名，传「全部」返回完整列表
 * @returns 筛选后的色号数组
 */
export function GetMardColorsBySeries(series: string): MardColor[] {
  if (series === '全部') {
    return MARDCOLORS
  }
  return MARDCOLORS.filter((item) => item.series === series)
}

/**
 * 根据色号查找 MARD 颜色（忽略大小写）
 * @param code 色号，如 A1
 * @returns 匹配色号，未找到则返回 null
 */
export function FindMardColorByCode(code: string): MardColor | null {
  const normalized = code.trim().toUpperCase()
  if (!normalized) {
    return null
  }
  return MARDCOLORS.find((item) => item.code.toUpperCase() === normalized) || null
}

/**
 * 根据 HEX 查找对应 MARD 色号（忽略大小写）
 * @param hex 颜色值
 * @returns 匹配的色号，未找到则返回 null
 */
export function FindMardColorByHex(hex: string): MardColor | null {
  const normalized = hex.trim().toUpperCase()
  return (
    MARDCOLORS.find((item) => item.hex.toUpperCase() === normalized) || null
  )
}

/**
 * 规范化 HEX 为大写格式
 * @param hex 原始颜色
 * @returns 大写 HEX
 */
export function NormalizeHex(hex: string): string {
  return hex.trim().toUpperCase()
}
